name: Component Detection

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.3
        with:
          filePath: 'src'